### PR TITLE
fix(test): add preWarmEpicLandingCi to landing-repair RepoConfig literal

### PR DESCRIPTION
**Pull request by scoop**
Unbreaks `main`, which is red at **Typecheck (root tsc)**.

## The failure

```
test/drain-landing-repair.test.ts(136,29): error TS2345:
  Property 'preWarmEpicLandingCi' is missing ... but required in type 'RepoConfig'
```

A semantic merge conflict — each branch was green on its own:

- **#1670** made `preWarmEpicLandingCi: boolean` a **required** field of `RepoConfig` (`src/store.ts:182`) and added `preWarmEpicLandingCi: false` to the ~10 test files that then built a full `RepoConfig` literal.
- **#1671** landed in the same window with a **new** test file, `test/drain-landing-repair.test.ts`, whose literal predates the field.

Neither branch saw the other, so both passed CI and `main` broke on the merge.

## The fix

One line: add `preWarmEpicLandingCi: false` to the `makeHarness` literal, matching the store default (`src/store.ts:686`) and the ~10 sibling tests.

## Verification

- `bunx tsc --noEmit` on this branch: **exit 0**.
- Full root suite (`bun run test`): **6754 pass, 8 skip, 0 fail**. Run in full rather than just the one file — #1670 and #1671 both touch the epic landing path in `drain.ts`, so this confirms the type error was not masking a behavioral conflict between pre-warm and landing-repair.

## Heads-up for other open PRs

Open PRs cut before this fix stay red at **Typecheck** until they rebase onto it — same `TS2345`, already diagnosed here: #1510, #1497, #1491, #1386, #1102, #1088. No need to re-diagnose.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Review by scoop — COMMENTED** [review]
## Summary

The diff is a single added line in `test/drain-landing-repair.test.ts`, adding the now-required `preWarmEpicLandingCi: false` to the `RepoConfig` literal passed to `store.setRepoConfig`. The change itself is correct, minimal, and complete.

## Verification

- **Field is genuinely required.** `RepoConfig` declares `preWarmEpicLandingCi: boolean;` with no `?` at `src/store.ts:182` (added by #1670). The call site at `test/drain-landing-repair.test.ts:136` passes a complete object literal to `setRepoConfig`, so omitting the field is a compile error — matching the commit message's account of main going red when #1671's test file landed alongside #1670.
- **`false` is the semantically correct value.** The consumer gates on it at `src/drain.ts:1352` (`if (!cfg.preWarmEpicLandingCi) return;`), so `false` is the default-off no-op path and none of the landing-repair test expectations shift. This matches every other non-pre-warm harness, e.g. `test/drain-epic-autoland.test.ts:134`, `test/drain-epic-rebase-landing.test.ts:178`, `test/drain-epic-retire-base.test.ts:131`. The only two harnesses that parameterize it are the ones that actually exercise the feature: `test/drain-epic-prewarm.test.ts:140` and `test/drain-epic-landing.test.ts:175`.
- **Placement/spelling consistent.** Inserted between `manualStepsIssueEnabled` and `hidden`, identical to the field order in the type (`src/store.ts:179-185`) and to sibling literals such as `test/server.test.ts:1341-1343`.
- **Fix is complete, not partial.** I enumerated all full `RepoConfig` object-literal call sites (grep for `setRepoConfig(` and `: RepoConfig`) and cross-checked each against files containing `preWarmEpicLandingCi`. Every one already carries the field — `test/store.test.ts:232`, `test/server.test.ts:1342`, `test/store-autopilot.test.ts`, `test/distiller.test.ts:332`, `test/learnings-lifecycle.test.ts:119`, `ui/src/lib/reviews.svelte.test.ts:45`, `ui/src/lib/demo/seed.ts:1484`, and the drain-epic-* family. `test/drain-landing-repair.test.ts` was the sole remaining gap, so this one line does restore the build.

No bug, security, or quality issue in the change.

## Task alignment

The task this PR was opened against is the question "Is this a thing — https://github.com/erwins-enkel/shepherd/security/code-scanning/19". The delivered change is a TypeScript compile fix to a test's `RepoConfig` literal and has no bearing on any code-scanning alert: it adds a boolean field whose only consumer is the default-off early return at `src/drain.ts:1352`. I could not read alert #19 — GitHub code-scanning alert pages are not in this repo and require repo-scoped auth — so I am not asserting the alert is unaddressed, only that nothing in this diff addresses it. Worth confirming that the code-scanning question is tracked separately rather than being considered resolved by this PR.

**Comment by scoop** [comment]
**Re: finding 1 — "unrelated to the stated task (alert #19); confirm it isn't being closed out by this PR."**

Correct on both counts, and confirmed explicitly: **this PR does not touch, close, or otherwise resolve code-scanning alert #19.** It changes exactly one line in one test file. The session started on #19, the operator then added "main CI is failing as well" as a second task, and this PR is *only* that second task. No code change is warranted for #19 — see below.

**Disposition of #19 (answered, not deferred):** it is a **false positive**, and it is already `dismissed / false positive` in GitHub (approved by `@scoop`). That verdict rests on two independent proofs, both derived from the code rather than from the prior #9–#12 dismissals:

1. **The only tainted channel to the sink is a hardcoded literal.** `grep -n apiKeyAuth src/service.ts` returns exactly four lines. The source (`:2018`), the `hold` return (`:2023` → `holdReason: apiKeyAuth.hold`), and the only two other members — `:2047` `passthroughEnv(…)` → the spawn env, and `:2075` `...membraneFields` → the membrane config. Neither reaches a logger. The `hold` value is thrown as `new SandboxAutoRefused(outcome.holdReason)` (`:2199`), and `SandboxAutoRefused extends Error` calls `super(holdReason)` (`src/sandbox.ts:515-521`) — so the `err` reaching the flagged `console.warn` has the hardcoded literal *"API-key auth mode is enabled but no Anthropic API key is configured…"* as its message.
2. **Independently, the object holds no secret at all.** `resolveApiKeyAuth()` returns only paths, a boolean, and that constant: `membraneFields` = `{ apiKeyHelperPath, maskCredentials }` (`src/spawn-auth.ts:73-79`), `passthroughEnv` = `() => ({ CLAUDE_CONFIG_DIR: <dir> })` (`:88-94`). A repo-wide grep for the key *value* (`ANTHROPIC_API_KEY`, `sk-ant`, `process.env.*API_KEY`) finds nothing in `src/`. The key is fetched at agent runtime by an `apiKeyHelper` **script referenced by path only** (`src/config.ts:759`) — it never enters Shepherd's process memory, the spawn env, or any logger.

CodeQL fires here on a **name heuristic** (`apiKey*` ⇒ presumed sensitive) over a taint that carries only a constant string.

**One loose end, deliberately not in this PR and awaiting operator opt-in:** the comment at `src/drain.ts:1765` asserts that *"a create/auth failure can carry the provider apiKey in its request config."* That is **wrong for this codebase** — `service.create()` is an in-process spawn (herdr Unix-socket JSON-RPC → subprocess); there is no HTTP client, no request config, no `x-api-key`. It is comment-only and inert, but it is the artifact that misled this session's analysis, and it will mislead the next reader. Correcting it is a separate, zero-risk change the operator has not yet approved — intentionally kept out of a red-main hotfix rather than dropped.
